Update README.md
The `withFormatter` function requires a `FormatterInterface` object, the example fails.

TypeError: Argument 1 passed to Laudis\Neo4j\ClientBuilder::withFormatter() must implement interface Laudis\Neo4j\Contracts\FormatterInterface, string given.